name: Github Actions CI
on: [push]

jobs:
  ionic-ci:
    name: ionic-ci
    runs-on: ubuntu-latest
    steps:

      - name: checkout latest commit
        uses: actions/checkout@master

      - name: npm install & build
        run: |
          npm install
          npm run build

      - name: npm lint
        run: |
          npm run lint

      # - name: npm test
      #   run: |
      #     npm run test

      # - name: npm e2e
      #   run: |
      #     npm run e2e

      # - name: npm generate
      #   run: |
      #     npm run generate