name: Github Actions CI
on: [push]

env:
  NODE_VERSION: '12.x'                # set this to the node version to use

jobs:
  ionic-ci:
    name: ionic-ci
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install & build
      run: |
        git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf ssh://git@github.com/
        npm ci
        npm run build

    - name: npm lint
      run: |
        npm run lint

      # - name: npm test
      #   run: |
      #     npm run test

      # - name: npm e2e
      #   run: |
      #     npm run e2e

      # - name: npm generate
      #   run: |
      #     npm run generate