name: Github Actions CI
on: [push]

env:
  NODE_VERSION: '12.x'                # set this to the node version to use

jobs:
  ionic-ci:
    name: ionic-ci
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} 

    - name: npm install & build
      run: |
        npm install
        npm run build

    - name: npm lint
      run: |
        npm run lint

      # - name: npm test
      #   run: |
      #     npm run test

      # - name: npm e2e
      #   run: |
      #     npm run e2e

      # - name: npm generate
      #   run: |
      #     npm run generate